### ISSUE TITLE
"Unsupported Bootloader" error on SCH-I545 bootloader OC1

### ISSUE THREAD

**Issue by sam86314** [jb881122/out-of-range#1]
Upon trying to patch the aboot.img from my SCH-I545, I get the unsupported bootloader error.

My phone has bootloader "VRUGOC1" and is running Android 5.0.1 (rooted, obviously).

I looked through the aboot.img in a hex editor, and I found the string relating to the old Loki patch, but I didn't see any strings relating to this exploit.

Here's my aboot.img (in a zip file because GitHub won't let me attach a .img file.)

[aboot.zip](https://github.com/jb881122/out-of-range/files/15448685/aboot.zip)

**Comment by jb881122** [comment]
I added that bootloader in the latest release. I tested it and it works for me, but try it out and make sure it works for you too before this issue gets closed.

**Comment by sam86314** [comment]
Works now. Thank you so much.

Was there anything weird about that bootloader? I saw an OC1 bootloader listed if I did "oor -l", but it had FAJP or something before it.

**Comment by jb881122** [comment]
There was nothing weird about your bootloader. At this point, I have a script that can automatically generate a config given an S4 bootloader, as they are very similar between versions. What usually takes time is testing them, as I have a different model and I need to use tricks to actually boot with those bootloaders. The main reason some bootloaders are unsupported is simply because I didn't find them online (so I appreciate you providing that).

The bootloaders with "FAJP" in them are from combination ROMs, which are used by Samsung for testing devices in their factories. Some of them get out on the internet, as they can be useful for other things like downgrading Android or rooting if the bootloader is locked.
